### ISSUE TITLE
Question: How to execute actions without data input ?

### ISSUE THREAD

**Issue by gaboesquivel** [greymass/eosio-core#12]
At the moment `Action.from` expects `data` as `Struct` instance and it fails if undefined or empty. 

How to execute actions that take no input ?

![image](https://user-images.githubusercontent.com/391270/122220924-0aed9980-ce6e-11eb-9566-4642d5355e0f.png)

**Comment by jnordberg** [comment]
`data = Bytes.from(0)` should do it

**Comment by gaboesquivel** [comment]
Thanks
