### ISSUE TITLE
Document IDE Debugging Setup

### ISSUE THREAD

**Issue by ericpassmore** [greymass/eosio-core#36]
Ok for me to add a new directory and file docs/IDE_Debug.md and link from README? 

I'm not used to using make files for building TS/JS packages. Took some research to get the options right for Webstorm. Want to write down my notes for my future self and others. If this is ok, assign the issue to me and I'll build the pull request.

**Comment by jnordberg** [comment]
No objections. Heads up though that the `docs/` folder is currently treated as a build artifact so that needs to be reconfigured (see `docs` and `deploy-site` targets in Makefile). I suggest renaming that to `docs_build/` or similar.

**Comment by jnordberg** [comment]
Closed by #39
